//LOGIN
export const SIGNIN_START = "SIGNIN_START";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
//SIGNUP
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
//GOOGLE
export const GOOGLE_AUTH_START = "GOOGLE_AUTH_START";
export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";

//MENU
export const MENU_LOAD_START = "MENU_LOAD_START";
export const MENU_LOAD_SUCCESS = "MENU_LOAD_SUCCESS";
export const MENU_LOAD_FAIL = "MENU_LOAD_FAIL";

//ORDER
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const EDIT_ORDER = "EDIT_ORDER";
export const CANCEL_ORDER = "CANCEL_ORDER";
export const CONFIRM_ORDER = " CONFIRM_ORDER";
export const MAKE_PAYMENT = " MAKE_PAYMENT";
export const PAYMENT_SUCCESS = " PAYMENT_SUCCESS";
export const PAYMENT_FAIL = " PAYMENT_FAIL";
export const PLACE_ORDER = " PLACE_ORDER";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";
